
State:
  name: string, non-null, indexed
  task_id: uuid

Task:
  name: string, non-null
  description: json

Estimate:
  type: string
  mode: float
  extreme: float
  rationale: string
  task_id: uuid

Action:
  actual_time: float
  task_id: uuid
  verification: string
