
State:
  name: string, non-null, indexed
  text: string
  task_id: string

Person:
  emoji: string

Estimate:
  type: string
  mode: float
  extreme: float
  rationale: string
  task_id: string
  person_id: uuid

Action:
  actual_time: float
  task_id: string
  person_id: uuid
